openapi: 3.0.0
info:
  title: OCR API
  version: 0.1.0
  description: >
    HTTP API used by the frontend to submit health report files for OCR.
    The backend is the single integration point; it may call internal or external OCR services.

paths:
  /api/ocr:
    post:
      summary: Submit a health report file for OCR
      description: >
        Accepts one or more image/PDF files representing a single health report and starts OCR processing.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Health report image/PDF files (typically 1 per request).
      responses:
        '202':
          description: OCR request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  status:
                    type: string
                    enum: [queued, processing]
        '400':
          description: Validation error (unsupported format, size too large, etc.)
        '500':
          description: Internal error while enqueuing or starting OCR

  /api/ocr/{requestId}:
    get:
      summary: Get OCR request status and result
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OCR request found
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  status:
                    type: string
                    enum: [queued, processing, completed, error]
                  errorCode:
                    type: string
                    nullable: true
                  errorMessage:
                    type: string
                    nullable: true
                  result:
                    type: object
                    nullable: true
                    description: Structured OCR result when status = completed.
        '404':
          description: Request not found

